### ISSUE TITLE
Not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by weberam2** [KkEi34/confluence-to-obsidian-plugin#1]
Hi!
First of all, I just wanted to say thanks for making this! 
I have a lab and we have our wiki on Confluence. However, like all things, my research institute may decide not to pay for it, or Confluence won't be around forever... you know.
So I want a way to backup and maybe import to Obsidian.

I think I followed your instructions, and was able to import.

However, it only lists a couple folders but no files :(

pandoc is installed... not sure what else I could try.

**Comment by KkEi34** [comment]
Hi!
Thanks for trying the plugin.
Please update the plugin to the  v. 0.2.4.
Let me know, if you encounter any problems.

Best of luck!
