### ISSUE TITLE
New plugin name requirements

### ISSUE THREAD

**Issue by joethei** [KkEi34/confluence-to-obsidian-plugin#3]
Hi @KkEi34

Per our [developer policies](https://docs.obsidian.md/Developer+policies),
please ensure that your plugin's name does not include the word "Obsidian".
In addition, the plugin name should not include the word "Plugin", as that is unecessary duplication.
We have already modified the name of your plugin to "Confluence Import" in our records.

To maintain compliance, take the following actions:

1. Modify the manifest.json file in your plugin repository.
2. Generate a new release for your plugin to ensure users download the updated manifest.

If you have a idea for a different plugin name, you may also submit a pull request to the [obsidianmd/obsidian-releases](https://github.com/obsidianmd/obsidian-releases) repository.

Thank you for your cooperation.
— the Obsidian team

**Comment by KkEi34** [comment]
Hi @joethei,

Thanks for updating the plugin name in the [obsidianmd/obsidian-releases](https://github.com/obsidianmd/obsidian-releases) repository. 

I changed the plugin name to 'Confluence Import' in the `manifest.json`.

Regards,
K.
