### ISSUE TITLE
Does not work on macOS

### ISSUE THREAD

**Issue by hiiroo** [KkEi34/confluence-to-obsidian-plugin#4]
Hello, thanks for the plugin. I've just tried it on macOS (15.0). However, it does not import anything and folder is empty.

- I checked if obsidian has full disk access but it did not affect the situation.
- pandoc was installled

**Comment by KkEi34** [comment]
Hello,

Thank you for trying the plugin. I checked it on Sequoia and found no issues.

Could you please open the developer tools using Command + Option + I and share any logs? Alternatively, you can provide a Confluence space export with test data so I can attempt to reproduce the problem.

Thank you!
PS.
What version of pandoc are you using? (pandoc -v)

**Comment by hiiroo** [comment]
Hello again,

I have tried and got some log outputs:

```
plugin:confluence-to-obsidian:12434 Using source: <HOME>/Downloads/Other/CFExportTest
plugin:confluence-to-obsidian:12434 Using destination: <HOME>/Library/Mobile Documents/iCloud~md~obsidian/Documents/<The Vault>
plugin:confluence-to-obsidian:12434 Parsing files ...
plugin:confluence-to-obsidian:12434 Found 145 files
plugin:confluence-to-obsidian:12434 Parsing ... <HOME>/Downloads/Other/CFExportTest/SRP/19136727.html
plugin:confluence-to-obsidian:12434 Making Markdown ... <HOME>/Library/Mobile Documents/iCloud~md~obsidian/Documents/<The Vault>/SRP/<Name of the Space>/<Name of the Space>.md
plugin:confluence-to-obsidian:12434 /bin/sh: /usr/local/bin/pandoc: No such file or directory

node:fs:448 Uncaught Error: ENOENT: no such file or directory, open '<HOME>/Library/Mobile Documents/iCloud~md~obsidian/Documents/<The Vault>/SRP/<Name of the Space>/<Name of the Space>.md'
    at Object.readFileSync (node:fs:448:20)
    at t.readFileSync (node:electron/js2c/node_init:2:9900)
    at _App.writeMarkdownFile (plugin:confluence-to-obsidian:12687:38)
    at _App.convertPage (plugin:confluence-to-obsidian:12662:10)
    at eval (plugin:confluence-to-obsidian:12647:21)
    at _App.convert (plugin:confluence-to-obsidian:12648:9)
    at Bootstrap.run (plugin:confluence-to-obsidian:12749:16)
    at ImportSpaceModal.eval [as onSubmit] (plugin:confluence-to-obsidian:12784:17)
    at eval (plugin:confluence-to-obsidian:12802:12)
    at HTMLButtonElement.<anonymous> (app.js:1:1484574)
```

and, here is the `pandoc -v` output:

```
pandoc 3.4
Features: +server +lua
Scripting engine: Lua 5.4
```

Thanks in advance.

**Comment by KkEi34** [comment]
Hello,

Thank you for providing the logs.
The plugin assumes that `pandoc` is located in `/usr/local/bin`, where it is installed by default with `brew install pandoc`.
You can use `which pandoc` in the terminal to check the location of `pandoc`.

I hope this helps!
